"""Language configuration for the code identifiers endpoint."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class LanguageConfig:
    key: str
    display_name: str
    color: str
    extensions: Sequence[str]
    strip_patterns: Sequence[re.Pattern[str]]  # Remove before extraction
    identifier_patterns: Sequence[re.Pattern[str]]  # Extract from these only
    keywords: frozenset[str]


# Common patterns to strip
STRIP_COMMENTS = [
    re.compile(r"/\*.*?\*/", re.DOTALL),
    re.compile(r"//.*?$", re.MULTILINE),
    re.compile(r"#.*?$", re.MULTILINE),
]
STRIP_STRINGS = [
    re.compile(r'"""[\s\S]*?"""'),
    re.compile(r"'''[\s\S]*?'''"),
    re.compile(r'"(?:[^"\\]|\\.)*"'),
    re.compile(r"'(?:[^'\\]|\\.)*'"),
    re.compile(r"`(?:[^`\\]|\\.)*`"),
]
STRIP_ANNOTATIONS = [re.compile(r"^\s*@\w+.*$", re.MULTILINE)]


LANGUAGE_CONFIGS: Sequence[LanguageConfig] = (
    LanguageConfig(
        key="python",
        display_name="Python",
        color="#3572A5",
        extensions=(".py",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            re.compile(r"^(?:from|import)\s+.*$", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"^\s*def\s+([a-z_][a-z0-9_]*)\s*\(", re.MULTILINE | re.IGNORECASE),
            re.compile(r"^\s*async\s+def\s+([a-z_][a-z0-9_]*)\s*\(", re.MULTILINE | re.IGNORECASE),
            re.compile(r"^\s*class\s+([a-z_][a-z0-9_]*)", re.MULTILINE | re.IGNORECASE),
            re.compile(r"^[ \t]*([a-z_][a-z0-9_]*)\s*=", re.MULTILINE),
            re.compile(r"\bself\.([a-z_][a-z0-9_]*)\s*=", re.IGNORECASE),
        ),
        keywords=frozenset(
            {
                "and",
                "as",
                "assert",
                "async",
                "await",
                "break",
                "class",
                "continue",
                "def",
                "del",
                "elif",
                "else",
                "except",
                "finally",
                "for",
                "from",
                "global",
                "if",
                "import",
                "in",
                "is",
                "lambda",
                "nonlocal",
                "not",
                "or",
                "pass",
                "raise",
                "return",
                "try",
                "while",
                "with",
                "yield",
                "true",
                "false",
                "none",
                "self",
                "cls",
            }
        ),
    ),
    LanguageConfig(
        key="javascript",
        display_name="JavaScript",
        color="#f1e05a",
        extensions=(".js", ".jsx"),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            re.compile(r"^import\s+.*?[;\n]", re.MULTILINE),
            re.compile(r"^export\s+(?:default\s+)?(?=class|function)", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\b(?:const|let|var)\s+([a-z_$][a-z0-9_$]*)\s*=", re.IGNORECASE),
            re.compile(r"\bfunction\s+([a-z_$][a-z0-9_$]*)\s*\(", re.IGNORECASE),
            re.compile(r"\bclass\s+([a-z_$][a-z0-9_$]*)", re.IGNORECASE),
            re.compile(r"(?:^|[;{])\s*(?:async\s+)?([a-z_$][a-z0-9_$]*)\s*\([^)]*?\)\s*{", re.MULTILINE | re.IGNORECASE),
            re.compile(
                r"^\s*(?:static\s+)?([a-z_$][a-z0-9_$]*)\s*[:=]\s*(?:async\s+)?(?:\([^)]*\)\s*=>|function\s*\()",
                re.MULTILINE | re.IGNORECASE,
            ),
            re.compile(r"^\s*export\s+default\s+function\s+([a-z_$][a-z0-9_$]*)", re.MULTILINE | re.IGNORECASE),
        ),
        keywords=frozenset(
            {
                "break",
                "case",
                "catch",
                "class",
                "const",
                "continue",
                "debugger",
                "default",
                "delete",
                "do",
                "else",
                "export",
                "extends",
                "finally",
                "for",
                "function",
                "if",
                "import",
                "in",
                "instanceof",
                "let",
                "new",
                "return",
                "super",
                "switch",
                "this",
                "throw",
                "try",
                "typeof",
                "var",
                "void",
                "while",
                "with",
                "yield",
                "async",
                "await",
                "true",
                "false",
                "null",
                "undefined",
            }
        ),
    ),
    LanguageConfig(
        key="typescript",
        display_name="TypeScript",
        color="#2b7489",
        extensions=(".ts", ".tsx"),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            re.compile(r"^import\s+.*?[;\n]", re.MULTILINE),
            re.compile(r"^export\s+(?:default\s+)?(?=class|function|interface|type)", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\b(?:const|let|var)\s+([a-z_$][a-z0-9_$]*)\s*[:=]", re.IGNORECASE),
            re.compile(r"\bfunction\s+([a-z_$][a-z0-9_$]*)\s*[<(]", re.IGNORECASE),
            re.compile(r"\bclass\s+([a-z_$][a-z0-9_$]*)", re.IGNORECASE),
            re.compile(r"\b(?:interface|type|enum)\s+([a-z_$][a-z0-9_$]*)", re.IGNORECASE),
            re.compile(
                r"(?:^|[;{])\s*(?:public\s+|private\s+|protected\s+)?(?:async\s+)?([a-z_$][a-z0-9_$]*)\s*\([^)]*?\)\s*[:\w\s\[\]<>?,.=]*\s*{",
                re.MULTILINE | re.IGNORECASE,
            ),
            re.compile(
                r"^\s*(?:public\s+|private\s+|protected\s+|readonly\s+|static\s+)*(?:declare\s+)?([a-z_$][a-z0-9_$]*)\s*[:=]",
                re.MULTILINE | re.IGNORECASE,
            ),
            re.compile(r"^\s*export\s+default\s+class\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE),
        ),
        keywords=frozenset(
            {
                "abstract",
                "any",
                "as",
                "async",
                "await",
                "boolean",
                "break",
                "case",
                "catch",
                "class",
                "const",
                "constructor",
                "continue",
                "declare",
                "default",
                "delete",
                "do",
                "else",
                "enum",
                "export",
                "extends",
                "false",
                "finally",
                "for",
                "from",
                "function",
                "if",
                "implements",
                "import",
                "in",
                "interface",
                "is",
                "keyof",
                "let",
                "module",
                "namespace",
                "new",
                "null",
                "number",
                "object",
                "of",
                "private",
                "protected",
                "public",
                "readonly",
                "return",
                "static",
                "string",
                "super",
                "switch",
                "this",
                "throw",
                "true",
                "try",
                "type",
                "typeof",
                "undefined",
                "var",
                "void",
                "while",
                "with",
                "yield",
            }
        ),
    ),
    LanguageConfig(
        key="java",
        display_name="Java",
        color="#b07219",
        extensions=(".java",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            *STRIP_ANNOTATIONS,
            re.compile(r"^import\s+.*?;", re.MULTILINE),
            re.compile(r"^package\s+.*?;", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)"),
            re.compile(r"\b(?:interface|enum|record)\s+([A-Za-z_][A-Za-z0-9_]*)"),
            re.compile(r"\b([A-Za-z_][\w<>\[\]]*?)\s+([a-z_][a-z0-9_]*)\s*\(", re.IGNORECASE),
            re.compile(r"\b([A-Za-z_][\w<>\[\]]*?)\s+([a-z_][a-z0-9_]*)\s*[=;]", re.IGNORECASE),
        ),
        keywords=frozenset(
            {
                "abstract",
                "assert",
                "boolean",
                "break",
                "byte",
                "case",
                "catch",
                "char",
                "class",
                "continue",
                "default",
                "do",
                "double",
                "else",
                "enum",
                "extends",
                "final",
                "finally",
                "float",
                "for",
                "if",
                "implements",
                "import",
                "instanceof",
                "int",
                "interface",
                "long",
                "native",
                "new",
                "null",
                "package",
                "private",
                "protected",
                "public",
                "return",
                "short",
                "static",
                "super",
                "switch",
                "synchronized",
                "this",
                "throw",
                "throws",
                "transient",
                "try",
                "void",
                "volatile",
                "while",
                "var",
                "string",
                "true",
                "false",
            }
        ),
    ),
    LanguageConfig(
        key="kotlin",
        display_name="Kotlin",
        color="#A97BFF",
        extensions=(".kt", ".kts"),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            *STRIP_ANNOTATIONS,
            re.compile(r"^import\s+.*$", re.MULTILINE),
            re.compile(r"^package\s+.*$", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\bfun\s+([a-z_][a-z0-9_]*)\s*[<(]", re.IGNORECASE),
            re.compile(r"\b(?:val|var)\s+([a-z_][a-z0-9_]*)"),
            re.compile(r"\b(?:class|object|interface)\s+([A-Za-z_][A-Za-z0-9_]*)"),
        ),
        keywords=frozenset(
            {
                "as",
                "break",
                "by",
                "class",
                "companion",
                "const",
                "constructor",
                "continue",
                "do",
                "else",
                "enum",
                "false",
                "for",
                "fun",
                "if",
                "import",
                "in",
                "interface",
                "is",
                "null",
                "object",
                "package",
                "private",
                "protected",
                "public",
                "return",
                "sealed",
                "super",
                "this",
                "throw",
                "true",
                "try",
                "typealias",
                "val",
                "var",
                "when",
                "while",
            }
        ),
    ),
    LanguageConfig(
        key="csharp",
        display_name="C#",
        color="#178600",
        extensions=(".cs",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            *STRIP_ANNOTATIONS,
            re.compile(r"^using\s+.*?;", re.MULTILINE),
            re.compile(r"^namespace\s+.*$", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\b(?:class|struct|record|interface)\s+([A-Za-z_][A-Za-z0-9_]*)"),
            re.compile(r"\b([A-Za-z_][\w<>\[\],?]*)\s+([a-z_][a-z0-9_]*)\s*\(", re.IGNORECASE),
            re.compile(r"\b([A-Za-z_][\w<>\[\],?]*)\s+([a-z_][a-z0-9_]*)\s*[=;]", re.IGNORECASE),
            re.compile(r"\b([A-Za-z_][\w<>\[\],?]*)\s+([A-Z][A-Za-z0-9_]*)\s*{\s*get", re.IGNORECASE),
        ),
        keywords=frozenset(
            {
                "abstract",
                "as",
                "base",
                "bool",
                "break",
                "byte",
                "case",
                "catch",
                "char",
                "class",
                "const",
                "continue",
                "decimal",
                "default",
                "delegate",
                "do",
                "double",
                "else",
                "enum",
                "event",
                "explicit",
                "extern",
                "false",
                "finally",
                "fixed",
                "float",
                "for",
                "foreach",
                "goto",
                "if",
                "implicit",
                "in",
                "int",
                "interface",
                "internal",
                "is",
                "lock",
                "long",
                "namespace",
                "new",
                "null",
                "object",
                "operator",
                "out",
                "override",
                "params",
                "private",
                "protected",
                "public",
                "readonly",
                "ref",
                "return",
                "sbyte",
                "sealed",
                "short",
                "sizeof",
                "static",
                "string",
                "struct",
                "switch",
                "this",
                "throw",
                "true",
                "try",
                "typeof",
                "uint",
                "ulong",
                "unchecked",
                "unsafe",
                "ushort",
                "using",
                "var",
                "virtual",
                "void",
                "volatile",
                "while",
            }
        ),
    ),
    LanguageConfig(
        key="go",
        display_name="Go",
        color="#00ADD8",
        extensions=(".go",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            re.compile(r"^import\s+(?:\([\s\S]*?\)|\".*?\")", re.MULTILINE),
            re.compile(r"^package\s+\w+", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\bfunc\s+(?:\([^)]+\)\s*)?([a-z_][a-z0-9_]*)\s*\(", re.IGNORECASE),
            re.compile(r"\b(?:var|const)\s+([a-z_][a-z0-9_]*)"),
            re.compile(r"([a-z_][a-z0-9_]*)\s*:="),
            re.compile(r"^\s*type\s+([A-Z][A-Za-z0-9_]*)", re.MULTILINE),
        ),
        keywords=frozenset(
            {
                "break",
                "case",
                "chan",
                "const",
                "continue",
                "default",
                "defer",
                "else",
                "fallthrough",
                "for",
                "func",
                "go",
                "goto",
                "if",
                "import",
                "interface",
                "map",
                "package",
                "range",
                "return",
                "select",
                "struct",
                "switch",
                "type",
                "var",
                "nil",
                "true",
                "false",
                "err",
            }
        ),
    ),
    LanguageConfig(
        key="ruby",
        display_name="Ruby",
        color="#701516",
        extensions=(".rb",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
        ),
        identifier_patterns=(
            re.compile(r"^\s*def\s+([a-z_][a-z0-9_!?]*)", re.MULTILINE),
            re.compile(r"@([a-z_][a-z0-9_]*)"),
            re.compile(r"^\s*(?:class|module)\s+([A-Z][A-Za-z0-9_:]*)", re.MULTILINE),
        ),
        keywords=frozenset(
            {
                "alias",
                "and",
                "begin",
                "break",
                "case",
                "class",
                "def",
                "do",
                "else",
                "elsif",
                "end",
                "ensure",
                "false",
                "for",
                "if",
                "in",
                "module",
                "next",
                "nil",
                "not",
                "or",
                "redo",
                "rescue",
                "retry",
                "return",
                "self",
                "super",
                "then",
                "true",
                "undef",
                "unless",
                "until",
                "when",
                "while",
                "yield",
            }
        ),
    ),
    LanguageConfig(
        key="php",
        display_name="PHP",
        color="#4F5D95",
        extensions=(".php",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            re.compile(r"^use\s+.*?;", re.MULTILINE),
            re.compile(r"^namespace\s+.*?;", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\bfunction\s+([a-z_][a-z0-9_]*)\s*\(", re.IGNORECASE),
            re.compile(r"\$([a-z_][a-z0-9_]*)"),
            re.compile(r"^\s*(?:class|interface|trait)\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE),
        ),
        keywords=frozenset(
            {
                "abstract",
                "and",
                "array",
                "as",
                "break",
                "callable",
                "case",
                "catch",
                "class",
                "clone",
                "const",
                "continue",
                "declare",
                "default",
                "die",
                "do",
                "echo",
                "else",
                "elseif",
                "empty",
                "endfor",
                "endforeach",
                "endif",
                "endswitch",
                "endwhile",
                "eval",
                "exit",
                "extends",
                "final",
                "finally",
                "for",
                "foreach",
                "function",
                "global",
                "goto",
                "if",
                "implements",
                "include",
                "instanceof",
                "insteadof",
                "interface",
                "isset",
                "list",
                "namespace",
                "new",
                "or",
                "print",
                "private",
                "protected",
                "public",
                "require",
                "return",
                "static",
                "switch",
                "throw",
                "trait",
                "try",
                "unset",
                "use",
                "var",
                "while",
                "xor",
                "yield",
                "this",
                "self",
            }
        ),
    ),
    LanguageConfig(
        key="swift",
        display_name="Swift",
        color="#F05138",
        extensions=(".swift",),
        strip_patterns=(
            *STRIP_STRINGS,
            *STRIP_COMMENTS,
            *STRIP_ANNOTATIONS,
            re.compile(r"^import\s+\w+", re.MULTILINE),
        ),
        identifier_patterns=(
            re.compile(r"\bfunc\s+([a-z_][a-z0-9_]*)\s*[<(]", re.IGNORECASE),
            re.compile(r"\b(?:let|var)\s+([a-z_][a-z0-9_]*)"),
            re.compile(r"^\s*(?:class|struct|enum|protocol)\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE),
        ),
        keywords=frozenset(
            {
                "as",
                "break",
                "case",
                "catch",
                "class",
                "continue",
                "defer",
                "deinit",
                "do",
                "else",
                "enum",
                "extension",
                "fallthrough",
                "false",
                "for",
                "func",
                "guard",
                "if",
                "import",
                "in",
                "init",
                "inout",
                "internal",
                "let",
                "nil",
                "open",
                "operator",
                "private",
                "protocol",
                "public",
                "repeat",
                "return",
                "self",
                "static",
                "struct",
                "subscript",
                "switch",
                "throw",
                "throws",
                "true",
                "try",
                "typealias",
                "var",
                "where",
                "while",
            }
        ),
    ),
)


EXTENSION_TO_LANG = {ext: cfg.key for cfg in LANGUAGE_CONFIGS for ext in cfg.extensions}
LANGUAGE_COLORS = {cfg.key: cfg.color for cfg in LANGUAGE_CONFIGS}
LANGUAGE_NAMES = {cfg.key: cfg.display_name for cfg in LANGUAGE_CONFIGS}
LANG_MAP = {cfg.key: cfg for cfg in LANGUAGE_CONFIGS}


__all__ = [
    "EXTENSION_TO_LANG",
    "LANGUAGE_COLORS",
    "LANGUAGE_CONFIGS",
    "LANGUAGE_NAMES",
    "LANG_MAP",
    "LanguageConfig",
]
